version: "3.8"
services:
  db:
    image: postgres:14.11
    container_name: db
    restart: always
    env_file:
      - ./docker/development/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - "5432"
  redis:
    container_name: redis
    image: redis:7.2.4
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379:6379
    depends_on:
      db:
        condition: service_started
  app:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
      target: app_build
    entrypoint: bash -c "rm -rf tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: app
    image: rails-7.1.3
    restart: always
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    links:
      - db
      - redis
    ports:
      - 3000:3000
    volumes:
      - .:/rails
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails/node_modules
    env_file:
      - ./docker/development/.env
  sidekiq:
    build:
      context: .
      dockerfile: ./docker/development/Dockerfile
      target: app_build
    command: bundle exec sidekiq -e development -C config/sidekiq.yml -v
    image: sidekiq-7.2.2
    container_name: sidekiq
    depends_on:
      - app
    volumes:
      - .:/rails
    env_file:
      - ./docker/development/.env
volumes:
  db_data:
    driver: local
  redis:
  gem_cache:
  node_modules:
